/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.helloandroid.android.musicdroid3;

public final class R {
    public static final class anim {
        public static final int selected=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int menupause=0x7f020001;
        public static final int menuplay=0x7f020002;
        public static final int menuskipb=0x7f020003;
        public static final int menuskipf=0x7f020004;
        public static final int menustop=0x7f020005;
        public static final int playbackpause=0x7f020006;
        public static final int playbackstart=0x7f020007;
        public static final int transparent_background=0x7f020008;
    }
    public static final class id {
        public static final int pause=0x7f070000;
        public static final int skipb=0x7f070001;
        public static final int skipf=0x7f070002;
        public static final int stop=0x7f070003;
        public static final int text1=0x7f070004;
    }
    public static final class layout {
        public static final int controls=0x7f030000;
        public static final int song_item=0x7f030001;
        public static final int songlist=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class style {
        public static final int Theme=0x7f060000;
        public static final int Theme_Transparent=0x7f060001;
    }
}
